
### video upload
POST http://localhost:8080/api/v1/attach/public/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="aaa.mp4"

< C:\Users\USer\Videos\aaa.mp4


### Get Video by id
POST http://localhost:8080/api/v1/attach/get?id=f8aaa32e-e663-44af-b1d6-1a0573d8183a

