### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "muhammadyusufgapirov@gmail.com",
  "password": "12345"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "admin@gmail.com",
  "password": "1"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "oyatillo",
  "surname": "soliyev",
  "email": "oyatillo.soliyev03@gmail.com",
  "password": "777"
}


### Verification email
###
GET http://localhost:8080/api/v1/auth/email/verification/eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyMzU3NTAsImVtYWlsIjoibXVoYW1tYWR5dXN1ZmdhcGlyb3ZAZ21haWwuY29tIiwiZXhwIjoxNjg0MzIyMTUwLCJpc3MiOiJZb3V0dWJlIHRlc3QgcG9ydGFsaSJ9.LAcQP1vc2paaauG8dp3VIjWe9e7DEU8Ye61-LHgc3DSag6SWD8W4zOVQe8P4OOVEHnXKN1lKOWTOIbTP6rKAKw
Content-Type: application/json


