### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "uzokov29@gmail.com",
  "password": "7"
}

### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "admin@gmail.com",
  "password": "1"
}

### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Mamurjon",
  "surname": "Uzokov",
  "email": "uzokov29@gmail.com",
  "password": "7"
}
