### Category
POST localhost:8080/api/v1/category/private/adm
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjgxMzksImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQ0MTQ1MzksImlzcyI6IllvdXR1YmUgdGVzdCBwb3J0YWxpIn0.BHeOXDgSyVeit3mUMTQqwOU5O6JLch0DZFWc0PSclCukZ1IpAoDC1UpExdReu1MDyt1jlfLdvMct1HxdgBTsrw

{
  "name" : "LLLLL"
}


### Category update
PUT localhost:8080/api/v1/category/private/update/adm/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjgxMzksImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQ0MTQ1MzksImlzcyI6IllvdXR1YmUgdGVzdCBwb3J0YWxpIn0.BHeOXDgSyVeit3mUMTQqwOU5O6JLch0DZFWc0PSclCukZ1IpAoDC1UpExdReu1MDyt1jlfLdvMct1HxdgBTsrw

{
  "name" : "dddd"
}

### Category delete
DELETE localhost:8080/api/v1/category/private/delete/adm/5
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQzMjgxMzksImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQ0MTQ1MzksImlzcyI6IllvdXR1YmUgdGVzdCBwb3J0YWxpIn0.BHeOXDgSyVeit3mUMTQqwOU5O6JLch0DZFWc0PSclCukZ1IpAoDC1UpExdReu1MDyt1jlfLdvMct1HxdgBTsrw

### Category list
GET localhost:8080/api/v1/category/public/list
Content-Type:  application/json


