### Category
POST localhost:8080/api/v1/category/private/adm
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyMzc1NDgsImVtYWlsIjoibXVoYW1tYWR5dXN1ZmdhcGlyb3ZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQzMjM5NDgsImlzcyI6IllvdXR1YmUgdGVzdCBwb3J0YWxpIn0.1WE6AUBaEhe6b7p_uQFysfbeyw2Y2nmVsYjpK_XYj0wTPXdVQh8P0iRP5vtu_AVVwSzWlcLUIiPayLzClgyn7w


{
  "name" : "ssssss"
}


### Category
POST localhost:8080/api/v1/category/private/update/admin
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyMzc1NDgsImVtYWlsIjoibXVoYW1tYWR5dXN1ZmdhcGlyb3ZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2ODQzMjM5NDgsImlzcyI6IllvdXR1YmUgdGVzdCBwb3J0YWxpIn0.1WE6AUBaEhe6b7p_uQFysfbeyw2Y2nmVsYjpK_XYj0wTPXdVQh8P0iRP5vtu_AVVwSzWlcLUIiPayLzClgyn7w


{
  "name" : "aaaa"
}
