### Create profile
POST localhost:8080/api/v1/profile/private/create/adm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQyNDA5MzgsImVtYWlsIjoidXpva292MjlAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDMyNzMzOCwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.S9lexiCX0G-xHZM8x4wn3uOyPjiCzRKWk5x2rCMCFMiEYJoFGeNTeUKoS5mnSxu6lrmTFnIsuqZu_Sm7eSt4JQ
Content-Type:  application/json

### UpdatePsw profile
PUT localhost:8080/api/v1/profile/changePsw
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTEyMzYsImVtYWlsIjoibWFtdXJqb251em9rb3Y1NjhAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDY3NzYzNiwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.xRsFC3_jmpPq96NUhqhGTDFTT4kiNwnNGZGkwZyrEEj5sAKrdBAOKpb8l7pYpWUYSYA2Jm6tFazYrhVT4Y4Z3g
Content-Type:  application/json

{
  "psw": "2"
}

### UpdateEmail profile
PUT localhost:8080/api/v1/profile/changeEmail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTA5MTcsImVtYWlsIjoidXpva292MjlAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDY3NzMxNywiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.-KInpI0xPNcwHaXBVdKgT6s_q4NKnhePpJJTMJ6Qjxt6sAaPN4qg3aSyTVQ3AWHR1gGqusDiMwYyaFRNUCipCA
Content-Type:  application/json

{
  "newEmail": "mamurjonuzokov568@gmail.com"
}

### UpdateNameSurname profile
PUT localhost:8080/api/v1/profile/changeNameSurname
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTA5MTcsImVtYWlsIjoidXpva292MjlAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDY3NzMxNywiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.-KInpI0xPNcwHaXBVdKgT6s_q4NKnhePpJJTMJ6Qjxt6sAaPN4qg3aSyTVQ3AWHR1gGqusDiMwYyaFRNUCipCA
Content-Type:  application/json

{
  "name": "Ali",
  "surname": "Aliyev"
}

### UpdatePhoto profile
PUT localhost:8080/api/v1/profile/updatePhoto
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTIyNTUsImVtYWlsIjoidXpva292MjlAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDY3ODY1NSwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.RZ1k3zTMRFi-cgwPmyIu5J8qgsGXLg0PsaS6ZI-5r5BRFDoRUVIAoos5qncLLu5MYHdVN9QRKUB1-RPcQwjgQw
Content-Type:  application/json

{
  "photoId": "dd852e05-3114-40ef-b771-5f50166359eb"
}

### Get profile info
GET localhost:8080/api/v1/profile/getProfileDetail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTIyNTUsImVtYWlsIjoidXpva292MjlAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDY3ODY1NSwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.RZ1k3zTMRFi-cgwPmyIu5J8qgsGXLg0PsaS6ZI-5r5BRFDoRUVIAoos5qncLLu5MYHdVN9QRKUB1-RPcQwjgQw

### Create Admine profile
POST localhost:8080/api/v1/profile/private/create/adm
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODQ1OTIyNTUsImVtYWlsIjoidXpva292MjlAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NDY3ODY1NSwiaXNzIjoiWW91dHViZSB0ZXN0IHBvcnRhbGkifQ.RZ1k3zTMRFi-cgwPmyIu5J8qgsGXLg0PsaS6ZI-5r5BRFDoRUVIAoos5qncLLu5MYHdVN9QRKUB1-RPcQwjgQw
Content-Type:  application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "email@mail.com",
  "role": "ROLE_MODERATOR"
}